---
title: "Join Data"
author: "Tom"
format: html
editor: visual
---

## Libraries

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(patchwork)
```


## Joining Data 

```{r}
tom_path = "/courses/EDS214/group_project/2024/triple_threat/Raw_Data"

q2 <- read_csv(file.path(tom_path, "QuebradaCuenca2-Bisley.csv"))

prm <- read_csv(file.path(tom_path, "RioMameyesPuenteRoto.csv"))

q3_path = "/courses/EDS214/group_project/2024/triple_threat/Raw_Data"

q3 <- read_csv(file.path(q3_path, "QuebradaCuenca3-Bisley.csv"))

jorb_path <- "/courses/EDS214/group_project/2024/triple_threat/Raw_Data"

q1 <- read_csv(file.path(jorb_path, "QuebradaCuenca1-Bisley.csv"))
```

## Cleaning Data

```{r}
q2 <- q2 %>% 
  clean_names() %>% 
  mutate(year = year(sample_date)) %>% 
  filter(year %in% c(1988:1995))


prm <- prm %>% 
  clean_names() %>% 
  mutate(year = year(sample_date)) %>% 
  filter(year %in% c(1988:1995))

q1 <- q1 |> 
  clean_names() |>
  mutate(year = year(sample_date)) |>
  filter(year %in% c(1988:1995))

q3_tidy <- q3 %>% 
  clean_names() %>% 
  mutate(year = year(sample_date)) %>%
  filter(year %in% c(1988:1995))
  
```

## Joining Data Sets

```{r}
q1q2_data <- full_join(q1, q2)
q1q2q3_data <- full_join(q1q2_data, q3_tidy)
all_data <- full_join(q1q2q3_data, prm)
```

## ggplot

```{r}
k_plot <- ggplot(all_data, aes(x = sample_date, y = k, color = sample_id)) +
  geom_line()

no3_plot <- ggplot(all_data, aes(x = sample_date, y = no3_n, color = sample_id)) +
  geom_line()


k_plot / no3_plot
```



