---
title: "mish_joindata_graph"
format: html
editor_options: 
  chunk_output_type: console
---

## Libraries

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(patchwork)
library(paletteer)
```

## Joining Data

```{r}
tom_path = "/courses/EDS214/group_project/2024/triple_threat/Raw_Data"

q2 <- read_csv(file.path(tom_path, "QuebradaCuenca2-Bisley.csv"))

prm <- read_csv(file.path(tom_path, "RioMameyesPuenteRoto.csv"))

q3_path = "/courses/EDS214/group_project/2024/triple_threat/Raw_Data"

q3 <- read_csv(file.path(q3_path, "QuebradaCuenca3-Bisley.csv"))

jorb_path <- "/courses/EDS214/group_project/2024/triple_threat/Raw_Data"

q1 <- read_csv(file.path(jorb_path, "QuebradaCuenca1-Bisley.csv"))
```

## Cleaning Data

```{r}
q2 <- q2 %>% 
  clean_names() %>% 
  mutate(year = year(sample_date)) %>% 
  filter(year %in% c(1988:1994))


prm <- prm %>% 
  clean_names() %>% 
  mutate(year = year(sample_date)) %>% 
  filter(year %in% c(1988:1994))

q1 <- q1 |> 
  clean_names() |>
  mutate(year = year(sample_date)) |>
  filter(year %in% c(1988:1994))

q3_tidy <- q3 %>% 
  clean_names() %>% 
  mutate(year = year(sample_date)) %>%
  filter(year %in% c(1988:1994))
  
```

## Joining Data Sets

```{r}
q1q2_data <- full_join(q1, q2)
q1q2q3_data <- full_join(q1q2_data, q3_tidy)
all_data <- full_join(q1q2q3_data, prm)
```

## ggplot

```{r}
year_labels <- seq(1988, 1995, 1)
```


```{r}
k_plot <- ggplot(all_data, aes(x = sample_date, y = k, color = sample_id)) +
  geom_line() +
  geom_vline(xintercept = as.numeric(as.Date("1989-09-18"), linetype = "dotted")) +
  scale_color_paletteer_d("palettetown::yanma") +
  scale_x_date(date_breaks = "1 year", date_minor_breaks = "1 month", date_label = "%Y") + theme_minimal() +
  scale_y_continuous(limits = c(0, 1.9), breaks = seq(0, 1.9, 0.3))  +
  labs(y = "K mg/L", color = "Watershed Sites") +
  theme(axis.title.x=element_blank(),
        legend.position= "blank")
  

no3_plot <- ggplot(all_data, aes(x = sample_date, y = no3_n, color = sample_id)) +
  scale_color_paletteer_d("palettetown::yanma") +
  geom_line()+
  geom_vline(xintercept = as.numeric(as.Date("1989-09-18"), linetype = "dotted")) +
  scale_x_date(date_breaks = "1 year", date_minor_breaks = "1 month", date_label = "%Y") +
  scale_y_continuous(limits = c(0, 600), breaks = seq(0, 600, 100)) +
  theme_minimal() +
  theme(legend.position = c(0.9, 0.75)) +
  labs( x = "Sample Year",
        y = "No3-N ug/L",
        color = "Watershed Sites")
  
  


k_plot / no3_plot

```
