---
title: "Tom's Document"
author: "Tom Gibbens-Matsuyama"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Load Libraries

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
```

## Load Q2 CSV File

```{r}
tom_path = "/courses/EDS214/group_project/2024/triple_threat/Raw_Data"

q2 <- read_csv(file.path(tom_path, "QuebradaCuenca2-Bisley.csv"))
```

## Load PRM CSV File

```{r}
prm <- read_csv(file.path(tom_path, "RioMameyesPuenteRoto.csv"))
```

## Clean Data

```{r}
q2 <- q2 %>% 
  clean_names() %>% 
  mutate(year = year(sample_date)) %>% 
  filter(year %in% c(1988:1995))


# data is now cleaned for the dates that we want. can call the variables we want when we ggplot  
```

## Clean PRM Data

```{r}
prm <- prm %>% 
  clean_names() %>% 
  mutate(year = year(sample_date)) %>% 
  filter(year %in% c(1988:1995))
```

## Joining Data

```{r}
data_join <- full_join(q2, prm)
```

## ggplotting

```{r}
ggplot(data_join, aes(x = sample_date, y = k, color = sample_id)) +
  geom_line()
  
```
